using System;

namespace Dangl.SchneidControl
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "0.1.1-beta0003";
        public static string CommitInfo => "Branch.develop.Sha.f0567910a2552b3369e0cdc5f7350ee6cdf466e2";
        public static string CommitDate => "2023-07-08";
        public static string CommitHash => "f0567910a2552b3369e0cdc5f7350ee6cdf466e2";
        public static string InformationalVersion => "0.1.1-beta.3+Branch.develop.Sha.f0567910a2552b3369e0cdc5f7350ee6cdf466e2";
        public static DateTime BuildDateUtc { get; } = new DateTime(2023, 7, 8, 20, 16, 23, DateTimeKind.Utc);
    }
}
